#!/usr/bin/env python3
import subprocess
import time
import subprocess
import psutil

"""
Budgie Wallpaper Switcher
Author: Jacob Vlijm
Copyright © 2017 Ubuntu Budgie Developers
Website: https://ubuntubudgie.org
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or any later version. This
program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License for more details. You
should have received a copy of the GNU General Public License along with this
program.  If not, see <http://www.gnu.org/licenses/>.
"""
    
def get_pid():
    try:
        return int(subprocess.check_output([
            "pgrep", "-f", "/opt/budgie-wswitcher/budgie-wswitcher/wswitcher-run",
            ]).decode("utf-8").strip())
    except subprocess.CalledProcessError:
        return subprocess.Popen("/opt/budgie-wswitcher/budgie-wswitcher/wswitcher-run").pid 

def getkey():
    data = subprocess.check_output([
        "dconf",
        "dump",
        "/com/solus-project/budgie-panel/applets/"
        ]).decode("utf-8").splitlines()
    try:
        match = [l for l in data if "Budgie Wallpaper Switcher" in l][0]
        watch = data.index(match)-3
        return data[watch][1:-1]
    except IndexError:
        pass

def run_wswitcher():
    # give dconf a few seconds to create the key
    time.sleep(3)
    key = getkey()
    while True:
        time.sleep(3)
        try:
            check = subprocess.check_output([
                "dconf",
                "dump",
                "/com/solus-project/budgie-panel/applets/"+key+"/"
                ]).decode("utf-8")
            if not check:
                break
        except TypeError:
            break

pid = get_pid()
run_wswitcher()
psutil.Process(pid).terminate()


