#!/usr/bin/env python3
import subprocess
import time
import subprocess
import psutil

def get_pid():
    try:
        return int(subprocess.check_output([
            "pgrep", "-f", "/opt/wmover/wmover/wmover_run",
            ]).decode("utf-8").strip())
    except subprocess.CalledProcessError:
        return subprocess.Popen("/opt/wmover/wmover/wmover_run").pid 

def getkey():
    data = subprocess.check_output([
        "dconf",
        "dump",
        "/com/solus-project/budgie-panel/applets/"
        ]).decode("utf-8").splitlines()
    try:
        match = [l for l in data if "WindowMover" in l][0]
        watch = data.index(match)-3
        return data[watch][1:-1]
    except IndexError:
        pass

def run_wmover():
    key = getkey()
    while True:
        time.sleep(3)
        try:
            if not subprocess.check_output([
                "dconf",
                "dump",
                "/com/solus-project/budgie-panel/applets/"+key+"/"
                ]).decode("utf-8"):
                break
        except TypeError:
            break

pid = get_pid()
run_wmover()
psutil.Process(pid).terminate()

