#!/usr/bin/env python3
import subprocess
import time
import subprocess
import psutil
import os
import wprviews_tools as pv 

"""
Budgie WindowPreviews
Author: Jacob Vlijm
Copyright=Copyright © 2017 Ubuntu Budgie Developers
Website=https://ubuntubudgie.org
This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or any later version. This
program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License for more details. You
should have received a copy of the GNU General Public License along with this
program.  If not, see <http://www.gnu.org/licenses/>.
"""

plugin_path = pv.plugin_path
dcpath = pv.dcpath

def get_pid():
    app = os.path.join(plugin_path, "wprviews_backgrounder")
    try:
        return int(subprocess.check_output([
            "pgrep", "-f", app,
            ]).decode("utf-8").strip())
    except subprocess.CalledProcessError:
        return subprocess.Popen(app).pid 

def run_wmover():
    # give dconf a few seconds to create the key
    time.sleep(3)
    key = pv.getkey()
    while True:
        time.sleep(3)
        try:
            # ok, ok, this should be fetched with help from wmovertools...
            check = subprocess.check_output([
                "dconf", "dump", dcpath+key+"/",
                ]).decode("utf-8")
            if not check:
                break
        except TypeError:
            break

pid = get_pid()
run_wmover()
psutil.Process(pid).terminate()
pv.empty_dir()

