#!/usr/bin/env python3
import time
import os
import subprocess

dropby_user = os.environ["USER"]
timer = "/tmp/" + dropby_user + "_keepdropbywin"


try:
    os.remove(timer)
except FileNotFoundError:
    pass


t = 0
while True:
    time.sleep(1)
    if not os.path.exists(timer):
        t = t + 1
    else:
        t = 0
    if t >= 6:
        subprocess.Popen(["/usr/bin/wmctrl", "-c", "dropby_popup"])
        break
